engines:
 duplication:
   enabled: true
   config:
     languages:
     - javascript:
   checks:
     Similar code:
       enabled: true
 eslint:
   enabled: true
   checks:
     import/extensions:
       enabled: false
     no-multiple-empty-lines:
       enabled: true
     linebreak-style:
       enabled: true
exclude_paths:
- "templates/"
- "client/"
- "clients/"
- "server/test/"
ratings:
  paths:
  - "server/**/*"