language: node_js

env:
- NODE_ENV="development"

node_js:
  - "stable"

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

after_success:
  - npm run build
  - npm run coveralls
  - npm run delete-dist