language: node_js

node_js:
  - "stable"

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cd server 
  - sequelize db:migrate 

after_success:
  - npm run build
  - npm run coveralls
  - npm run delete-dist