export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const SET_USER = 'SET_USER';
export const SET_USER_GROUPS = 'SET_USER_GROUPS';